server:
  port: 8080
spring:
  application:
    name: common-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mj1828/common-config.git
          username: *****
          password: *****
          default-label: master
          search-paths: config

